//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MessengerClient.ServiceMessenger {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceMessenger.IMessengerService", CallbackContract=typeof(MessengerClient.ServiceMessenger.IMessengerServiceCallback))]
    public interface IMessengerService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessengerService/Registration", ReplyAction="http://tempuri.org/IMessengerService/RegistrationResponse")]
        string Registration(string login, string password, string name, string surname, string path);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessengerService/Registration", ReplyAction="http://tempuri.org/IMessengerService/RegistrationResponse")]
        System.Threading.Tasks.Task<string> RegistrationAsync(string login, string password, string name, string surname, string path);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessengerService/Login", ReplyAction="http://tempuri.org/IMessengerService/LoginResponse")]
        System.Collections.Generic.Dictionary<string, string> Login([System.ServiceModel.MessageParameterAttribute(Name="login")] string login1, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessengerService/Login", ReplyAction="http://tempuri.org/IMessengerService/LoginResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, string>> LoginAsync(string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessengerService/Disconnect", ReplyAction="http://tempuri.org/IMessengerService/DisconnectResponse")]
        void Disconnect(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessengerService/Disconnect", ReplyAction="http://tempuri.org/IMessengerService/DisconnectResponse")]
        System.Threading.Tasks.Task DisconnectAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessengerService/GetUsers", ReplyAction="http://tempuri.org/IMessengerService/GetUsersResponse")]
        System.Collections.Generic.Dictionary<string, string>[] GetUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessengerService/GetUsers", ReplyAction="http://tempuri.org/IMessengerService/GetUsersResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, string>[]> GetUsersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessengerService/CreateChat", ReplyAction="http://tempuri.org/IMessengerService/CreateChatResponse")]
        void CreateChat(string name, string path, int admin, int[] users);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessengerService/CreateChat", ReplyAction="http://tempuri.org/IMessengerService/CreateChatResponse")]
        System.Threading.Tasks.Task CreateChatAsync(string name, string path, int admin, int[] users);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessengerService/GetChats", ReplyAction="http://tempuri.org/IMessengerService/GetChatsResponse")]
        System.Collections.Generic.Dictionary<string, string>[] GetChats(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessengerService/GetChats", ReplyAction="http://tempuri.org/IMessengerService/GetChatsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, string>[]> GetChatsAsync(int userId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMessengerServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMessengerService/CreateChatCallback")]
        void CreateChatCallback(int id, string name, int admin, string path);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMessengerServiceChannel : MessengerClient.ServiceMessenger.IMessengerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MessengerServiceClient : System.ServiceModel.DuplexClientBase<MessengerClient.ServiceMessenger.IMessengerService>, MessengerClient.ServiceMessenger.IMessengerService {
        
        public MessengerServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public MessengerServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public MessengerServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public MessengerServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public MessengerServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public string Registration(string login, string password, string name, string surname, string path) {
            return base.Channel.Registration(login, password, name, surname, path);
        }
        
        public System.Threading.Tasks.Task<string> RegistrationAsync(string login, string password, string name, string surname, string path) {
            return base.Channel.RegistrationAsync(login, password, name, surname, path);
        }
        
        public System.Collections.Generic.Dictionary<string, string> Login(string login1, string password) {
            return base.Channel.Login(login1, password);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, string>> LoginAsync(string login, string password) {
            return base.Channel.LoginAsync(login, password);
        }
        
        public void Disconnect(int id) {
            base.Channel.Disconnect(id);
        }
        
        public System.Threading.Tasks.Task DisconnectAsync(int id) {
            return base.Channel.DisconnectAsync(id);
        }
        
        public System.Collections.Generic.Dictionary<string, string>[] GetUsers() {
            return base.Channel.GetUsers();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, string>[]> GetUsersAsync() {
            return base.Channel.GetUsersAsync();
        }
        
        public void CreateChat(string name, string path, int admin, int[] users) {
            base.Channel.CreateChat(name, path, admin, users);
        }
        
        public System.Threading.Tasks.Task CreateChatAsync(string name, string path, int admin, int[] users) {
            return base.Channel.CreateChatAsync(name, path, admin, users);
        }
        
        public System.Collections.Generic.Dictionary<string, string>[] GetChats(int userId) {
            return base.Channel.GetChats(userId);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, string>[]> GetChatsAsync(int userId) {
            return base.Channel.GetChatsAsync(userId);
        }
    }
}
